// brands.js
// 91 brand configurations for Tide scraper
// renderMode: 'static' = CheerioCrawler (fast), 'browser' = PlaywrightCrawler (JS-heavy)
// saleSelectors: CSS selectors that confirm an active sale exists on the page

export const brands = [
  // ── HIGH STREET VALUE ──────────────────────────────────────────
  {
    id: 'B001', name: 'Next', cluster: 'High Street',
    womenswear: true, menswear: true, childrenswear: true,
    renderMode: 'browser',
    url: 'https://www.next.co.uk/',
    saleSelectors: ['.sale', '[data-testid="sale"]', 'h1'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B002', name: 'M&S', cluster: 'High Street',
    womenswear: true, menswear: true, childrenswear: true,
    renderMode: 'static',
    url: 'https://www.marksandspencer.com/',
    saleSelectors: ['h1', '.page-title', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B003', name: 'River Island', cluster: 'High Street',
    womenswear: true, menswear: true, childrenswear: false,
    renderMode: 'static',
    url: 'https://www.riverisland.com/',
    saleSelectors: ['h1', '[class*="sale"]', '[class*="promotion"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B004', name: 'New Look', cluster: 'High Street',
    womenswear: true, menswear: false, childrenswear: false,
    renderMode: 'static',
    url: 'https://www.newlook.com/uk/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B007', name: 'Evans', cluster: 'High Street',
    womenswear: true, menswear: false, childrenswear: false,
    renderMode: 'static',
    url: 'https://www.evans.co.uk/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B008', name: 'Bonmarche', cluster: 'High Street',
    womenswear: true, menswear: false, childrenswear: false,
    renderMode: 'static',
    url: 'https://www.bonmarche.co.uk/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B009', name: 'Peacocks', cluster: 'High Street',
    womenswear: true, menswear: true, childrenswear: true,
    renderMode: 'static',
    url: 'https://www.peacocks.co.uk/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },


  // ── CONTEMPORARY ───────────────────────────────────────────────
  {
    id: 'B011', name: 'Zara', cluster: 'Contemporary',
    womenswear: true, menswear: true, childrenswear: true,
    renderMode: 'browser',
    url: 'https://www.zara.com/uk/en/',
    saleSelectors: ['h1', '[class*="sale"]', '[data-qa-label]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B012', name: 'H&M', cluster: 'Contemporary',
    womenswear: true, menswear: true, childrenswear: true,
    renderMode: 'browser',
    url: 'https://www2.hm.com/en_gb/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B013', name: 'Mango', cluster: 'Contemporary',
    womenswear: true, menswear: true, childrenswear: false,
    renderMode: 'browser',
    url: 'https://shop.mango.com/gb/',
    saleSelectors: ['h1', '[class*="outlet"]', '[class*="sale"]'],
    confirmText: ['outlet', 'sale', 'up to', '% off'],
  },
  {
    id: 'B014', name: 'COS', cluster: 'Contemporary',
    womenswear: true, menswear: true, childrenswear: false,
    renderMode: 'browser',
    url: 'https://www.cos.com/en_gbp/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B015', name: 'Arket', cluster: 'Contemporary',
    womenswear: true, menswear: true, childrenswear: true,
    renderMode: 'browser',
    url: 'https://www.arket.com/en_gbp/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B016', name: '& Other Stories', cluster: 'Contemporary',
    womenswear: true, menswear: false, childrenswear: false,
    renderMode: 'browser',
    url: 'https://www.stories.com/en_gbp/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B017', name: 'Weekday', cluster: 'Contemporary',
    womenswear: true, menswear: true, childrenswear: false,
    renderMode: 'browser',
    url: 'https://www.weekday.com/en_gbp/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  // B018 Monki removed (May 2026): H&M Group wound Monki down as a standalone
  // brand through 2024 and folded its range into Weekday (B017), so it is no
  // longer a distinct shop in any centre. It was never mapped to a centre in
  // the dashboard PRESENCE matrix anyway — only auto-scraped and dropped.
  {
    id: 'B019', name: 'Hollister', cluster: 'Contemporary',
    womenswear: true, menswear: true, childrenswear: false,
    renderMode: 'browser',
    url: 'https://www.hollisterco.com/shop/uk/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B020', name: 'Abercrombie', cluster: 'Contemporary',
    womenswear: true, menswear: true, childrenswear: false,
    renderMode: 'browser',
    url: 'https://www.abercrombie.com/shop/uk/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },

  // ── CLASSIC BRITISH ────────────────────────────────────────────
  {
    id: 'B021', name: 'Fat Face', cluster: 'Classic British',
    womenswear: true, menswear: true, childrenswear: true,
    renderMode: 'static',
    url: 'https://www.fatface.com/',
    saleSelectors: ['h1', '[class*="sale"]', '[class*="promo"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B022', name: 'Joules', cluster: 'Classic British',
    womenswear: true, menswear: true, childrenswear: true,
    renderMode: 'static',
    url: 'https://www.joules.com/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B023', name: 'White Stuff', cluster: 'Classic British',
    womenswear: true, menswear: true, childrenswear: false,
    renderMode: 'static',
    url: 'https://www.whitestuff.com/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B024', name: 'Seasalt Cornwall', cluster: 'Classic British',
    womenswear: true, menswear: true, childrenswear: false,
    renderMode: 'static',
    url: 'https://www.seasaltcornwall.co.uk/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B025', name: 'Crew Clothing', cluster: 'Classic British',
    womenswear: true, menswear: true, childrenswear: false,
    renderMode: 'static',
    url: 'https://www.crewclothing.co.uk/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B026', name: 'Boden', cluster: 'Classic British',
    womenswear: true, menswear: true, childrenswear: true,
    renderMode: 'static',
    url: 'https://www.boden.co.uk/en-gb/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B027', name: 'Hobbs', cluster: 'Classic British',
    womenswear: true, menswear: false, childrenswear: false,
    renderMode: 'static',
    url: 'https://www.hobbs.co.uk/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B028', name: 'The White Company', cluster: 'Classic British',
    womenswear: true, menswear: true, childrenswear: true,
    renderMode: 'static',
    url: 'https://www.thewhitecompany.com/uk/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B029', name: 'Barbour', cluster: 'Classic British',
    womenswear: true, menswear: true, childrenswear: true,
    renderMode: 'static',
    url: 'https://www.barbour.com/uk/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B030', name: 'Cath Kidston', cluster: 'Classic British',
    womenswear: true, menswear: false, childrenswear: true,
    renderMode: 'static',
    url: 'https://www.cathkidston.com/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },

  // ── SMART/OCCASION ─────────────────────────────────────────────
  {
    id: 'B031', name: 'Phase Eight', cluster: 'Smart/Occasion',
    womenswear: true, menswear: false, childrenswear: false,
    renderMode: 'static',
    url: 'https://www.phase-eight.com/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B032', name: 'Whistles', cluster: 'Smart/Occasion',
    womenswear: true, menswear: false, childrenswear: false,
    renderMode: 'static',
    url: 'https://www.whistles.com/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B033', name: 'Reiss', cluster: 'Smart/Occasion',
    womenswear: true, menswear: true, childrenswear: false,
    renderMode: 'static',
    url: 'https://www.reiss.com/gb/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B036', name: 'Coast', cluster: 'Smart/Occasion',
    womenswear: true, menswear: false, childrenswear: false,
    renderMode: 'static',
    url: 'https://www.coast-stores.com/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B037', name: 'Monsoon', cluster: 'Smart/Occasion',
    womenswear: true, menswear: false, childrenswear: true,
    renderMode: 'static',
    url: 'https://www.monsoon.co.uk/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B038', name: 'Accessorize', cluster: 'Smart/Occasion',
    womenswear: true, menswear: false, childrenswear: false,
    renderMode: 'static',
    url: 'https://www.accessorize.com/uk/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },

  // ── PREMIUM CASUAL ─────────────────────────────────────────────
  {
    id: 'B041', name: 'Sweaty Betty', cluster: 'Premium Casual',
    womenswear: true, menswear: false, childrenswear: false,
    renderMode: 'static',
    url: 'https://www.sweatybetty.com/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B042', name: 'Lululemon', cluster: 'Premium Casual',
    womenswear: true, menswear: true, childrenswear: false,
    renderMode: 'browser',
    url: 'https://www.lululemon.co.uk/en-gb/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B043', name: 'Superdry', cluster: 'Premium Casual',
    womenswear: true, menswear: true, childrenswear: false,
    renderMode: 'static',
    url: 'https://www.superdry.com/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B044', name: 'Jack Wills', cluster: 'Premium Casual',
    womenswear: true, menswear: true, childrenswear: false,
    renderMode: 'static',
    url: 'https://www.jackwills.com/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B045', name: 'Hackett', cluster: 'Premium Casual',
    womenswear: false, menswear: true, childrenswear: false,
    renderMode: 'static',
    url: 'https://www.hackett.com/gb/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B046', name: 'Ralph Lauren', cluster: 'Premium Casual',
    womenswear: true, menswear: true, childrenswear: true,
    renderMode: 'browser',
    url: 'https://www.ralphlauren.co.uk/en/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B047', name: 'Tommy Hilfiger', cluster: 'Premium Casual',
    womenswear: true, menswear: true, childrenswear: true,
    renderMode: 'static',
    url: 'https://uk.tommy.com/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B048', name: 'Lacoste', cluster: 'Premium Casual',
    womenswear: true, menswear: true, childrenswear: true,
    renderMode: 'browser',
    url: 'https://www.lacoste.com/gb/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B049', name: 'Hugo Boss', cluster: 'Premium Casual',
    womenswear: true, menswear: true, childrenswear: false,
    renderMode: 'browser',
    url: 'https://www.hugoboss.com/uk/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B050', name: 'Levis', cluster: 'Premium Casual',
    womenswear: true, menswear: true, childrenswear: false,
    renderMode: 'static',
    url: 'https://www.levi.com/GB/en_GB/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },

  // ── OUTDOORSY/ACTIVE ───────────────────────────────────────────
  {
    id: 'B051', name: 'Nike', cluster: 'Active',
    womenswear: true, menswear: true, childrenswear: true,
    renderMode: 'browser',
    url: 'https://www.nike.com/gb/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B052', name: 'Adidas', cluster: 'Active',
    womenswear: true, menswear: true, childrenswear: true,
    renderMode: 'browser',
    url: 'https://www.adidas.co.uk/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B053', name: 'The North Face', cluster: 'Active',
    womenswear: true, menswear: true, childrenswear: false,
    renderMode: 'browser',
    url: 'https://www.thenorthface.com/en-gb/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B054', name: 'Berghaus', cluster: 'Active',
    womenswear: true, menswear: true, childrenswear: false,
    renderMode: 'static',
    url: 'https://www.berghaus.com/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B055', name: 'Columbia', cluster: 'Active',
    womenswear: true, menswear: true, childrenswear: false,
    renderMode: 'static',
    url: 'https://www.columbiasportswear.co.uk/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B056', name: 'Patagonia', cluster: 'Active',
    womenswear: true, menswear: true, childrenswear: false,
    renderMode: 'static',
    url: 'https://www.patagonia.com/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B057', name: 'Timberland', cluster: 'Active',
    womenswear: true, menswear: true, childrenswear: false,
    renderMode: 'static',
    url: 'https://www.timberland.co.uk/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B058', name: 'Craghoppers', cluster: 'Active',
    womenswear: true, menswear: true, childrenswear: true,
    renderMode: 'static',
    url: 'https://www.craghoppers.com/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B059', name: 'Regatta', cluster: 'Active',
    womenswear: true, menswear: true, childrenswear: true,
    renderMode: 'static',
    url: 'https://www.regatta.com/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B060', name: 'Mountain Warehouse', cluster: 'Active',
    womenswear: true, menswear: true, childrenswear: true,
    renderMode: 'static',
    url: 'https://www.mountainwarehouse.com/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },

  // ── FOOTWEAR ───────────────────────────────────────────────────
  {
    id: 'B061', name: 'Schuh', cluster: 'Footwear',
    womenswear: true, menswear: true, childrenswear: true,
    renderMode: 'static',
    url: 'https://www.schuh.co.uk/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B062', name: 'Dune London', cluster: 'Footwear',
    womenswear: true, menswear: true, childrenswear: false,
    renderMode: 'static',
    url: 'https://www.dunelondon.com/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B063', name: 'Office', cluster: 'Footwear',
    womenswear: true, menswear: true, childrenswear: false,
    renderMode: 'static',
    url: 'https://www.office.co.uk/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B064', name: 'Clarks', cluster: 'Footwear',
    womenswear: true, menswear: true, childrenswear: true,
    renderMode: 'static',
    url: 'https://www.clarks.co.uk/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B065', name: 'Kurt Geiger', cluster: 'Footwear',
    womenswear: true, menswear: true, childrenswear: false,
    renderMode: 'static',
    url: 'https://www.kurtgeiger.com/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B066', name: 'Skechers', cluster: 'Footwear',
    womenswear: true, menswear: true, childrenswear: true,
    renderMode: 'static',
    url: 'https://www.skechers.co.uk/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B067', name: 'UGG', cluster: 'Footwear',
    womenswear: true, menswear: true, childrenswear: true,
    renderMode: 'browser',
    url: 'https://www.ugg.com/uk/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B069', name: 'New Balance', cluster: 'Footwear',
    womenswear: true, menswear: true, childrenswear: true,
    renderMode: 'browser',
    url: 'https://www.newbalance.co.uk/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B070', name: 'FLANNELS', cluster: 'Footwear',
    womenswear: true, menswear: true, childrenswear: false,
    renderMode: 'browser',
    url: 'https://www.flannels.com/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },

  // ── ACCESSORIES ────────────────────────────────────────────────
  {
    id: 'B071', name: 'Pandora', cluster: 'Accessories',
    womenswear: true, menswear: false, childrenswear: false,
    renderMode: 'browser',
    url: 'https://uk.pandora.net/en/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B072', name: 'Fossil', cluster: 'Accessories',
    womenswear: true, menswear: true, childrenswear: false,
    renderMode: 'static',
    url: 'https://www.fossil.com/en-gb/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B073', name: 'Swarovski', cluster: 'Accessories',
    womenswear: true, menswear: false, childrenswear: false,
    renderMode: 'static',
    url: 'https://www.swarovski.com/en-GB/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B074', name: 'Radley', cluster: 'Accessories',
    womenswear: true, menswear: false, childrenswear: false,
    renderMode: 'static',
    url: 'https://www.radley.co.uk/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B075', name: 'Flying Tiger', cluster: 'Accessories',
    womenswear: true, menswear: true, childrenswear: true,
    renderMode: 'static',
    url: 'https://flyingtiger.com/en-gb/',
    saleSelectors: ['h1', '[class*="sale"]', '[class*="collection"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B076', name: 'Lush', cluster: 'Accessories',
    womenswear: true, menswear: true, childrenswear: false,
    renderMode: 'static',
    url: 'https://www.lush.com/uk/en/',
    saleSelectors: ['h1', '[class*="sale"]'],
    confirmText: ['sale', 'up to', '% off'],
  },
  {
    id: 'B077', name: 'John Lewis', cluster: 'Classic British',
    womenswear: true, menswear: true, childrenswear: true,
    renderMode: 'browser',
    url: 'https://www.johnlewis.com/',
    saleSelectors: ['h1', '[class*="sale"]', '[class*="Sale"]', '[data-testid*="sale"]'],
    confirmText: ['sale', 'up to', '% off', 'reduced'],
  },

  // ── MANUAL CHECK ────────────────────────────────────────────────────────────
  // These brands are visible in the Tide app but have no auto-scrape config.
  // Sale status is confirmed weekly via the admin console.
  // They have brand_sale_events rows in Supabase and appear in the admin UI,
  // but the scraper skips them (manualCheck: true).
  {
    id: 'B078', name: 'AllSaints', cluster: 'Premium Casual',
    womenswear: true, menswear: true, childrenswear: false,
    manualCheck: true, url: 'https://www.allsaints.com/',
  },
  {
    id: 'B079', name: 'Ann Summers', cluster: 'Accessories',
    womenswear: true, menswear: false, childrenswear: false,
    manualCheck: true, url: 'https://www.annsummers.com/',
  },
  {
    id: 'B080', name: 'Boux Avenue', cluster: 'Accessories',
    womenswear: true, menswear: false, childrenswear: false,
    manualCheck: true, url: 'https://www.bouxavenue.com/',
  },
  {
    id: 'B081', name: 'Bravissimo', cluster: 'Accessories',
    womenswear: true, menswear: false, childrenswear: false,
    manualCheck: true, url: 'https://www.bravissimo.com/',
  },
  {
    id: 'B083', name: 'Calvin Klein', cluster: 'Premium Casual',
    womenswear: true, menswear: true, childrenswear: false,
    manualCheck: true, url: 'https://www.calvinklein.co.uk/en/',
  },
  {
    id: 'B084', name: 'French Connection', cluster: 'Smart/Occasion',
    womenswear: true, menswear: true, childrenswear: false,
    manualCheck: true, url: 'https://www.frenchconnection.com/',
  },
  {
    id: 'B085', name: 'Gant', cluster: 'Premium Casual',
    womenswear: true, menswear: true, childrenswear: false,
    manualCheck: true, url: 'https://www.gant.co.uk/',
  },
  {
    id: 'B086', name: 'Jack & Jones', cluster: 'High Street',
    womenswear: false, menswear: true, childrenswear: false,
    manualCheck: true, url: 'https://www.jackjones.com/gb/en/',
  },
  {
    id: 'B088', name: 'Jigsaw', cluster: 'Smart/Occasion',
    womenswear: true, menswear: true, childrenswear: false,
    manualCheck: true, url: 'https://www.jigsaw-online.com/',
  },
  {
    id: 'B089', name: 'LK Bennett', cluster: 'Smart/Occasion',
    womenswear: true, menswear: false, childrenswear: false,
    manualCheck: true, url: 'https://www.lkbennett.com/',
  },
  {
    id: 'B090', name: 'Mint Velvet', cluster: 'Smart/Occasion',
    womenswear: true, menswear: false, childrenswear: false,
    manualCheck: true, url: 'https://www.mintvelvet.co.uk/',
  },
  {
    id: 'B092', name: 'Primark', cluster: 'High Street',
    womenswear: true, menswear: true, childrenswear: true,
    manualCheck: true, url: 'https://www.primark.com/en-gb/',
  },
  {
    id: 'B093', name: 'Uniqlo', cluster: 'Contemporary',
    womenswear: true, menswear: true, childrenswear: true,
    manualCheck: true, url: 'https://www.uniqlo.com/uk/en/',
  },
  {
    id: 'B094', name: 'Foot Locker', cluster: 'Footwear',
    womenswear: true, menswear: true, childrenswear: true,
    manualCheck: true, url: 'https://www.footlocker.co.uk/',
  },

  // ── ADDED 2026-05-26 (brand-presence rebuild) ─────────────────────────────
  // Candidates that passed the presence>=2 rule against the rebuilt 30-centre
  // matrix. Marked manualCheck because their UK sale pages are bot-protected
  // / JS-heavy enough that auto-scrape is unreliable; the admin console will
  // record their sale state weekly.
  {
    id: 'B095', name: 'Bershka', cluster: 'Contemporary',
    womenswear: true, menswear: true, childrenswear: false,
    manualCheck: true, url: 'https://www.bershka.com/gb/',
  },
  {
    id: 'B096', name: 'JD Sports', cluster: 'Active',
    womenswear: true, menswear: true, childrenswear: true,
    manualCheck: true, url: 'https://www.jdsports.co.uk/',
  },
  {
    id: 'B097', name: 'Sports Direct', cluster: 'Active',
    womenswear: true, menswear: true, childrenswear: true,
    manualCheck: true, url: 'https://www.sportsdirect.com/',
  },
  {
    id: 'B098', name: 'Footasylum', cluster: 'Footwear',
    womenswear: true, menswear: true, childrenswear: false,
    manualCheck: true, url: 'https://www.footasylum.com/',
  },
  {
    id: 'B099', name: 'Urban Outfitters', cluster: 'Contemporary',
    womenswear: true, menswear: true, childrenswear: false,
    manualCheck: true, url: 'https://www.urbanoutfitters.com/en-gb/',
  },
  {
    id: 'B100', name: "Victoria's Secret", cluster: 'Accessories',
    womenswear: true, menswear: false, childrenswear: false,
    manualCheck: true, url: 'https://www.victoriassecret.co.uk/',
  },
  {
    id: 'B101', name: 'Pull&Bear', cluster: 'Contemporary',
    womenswear: true, menswear: true, childrenswear: false,
    manualCheck: true, url: 'https://www.pullandbear.com/gb/',
  },
  {
    // The previous matrix-build pass only detected Diesel at 1 of 30 directories
    // and dropped it. The handover pre-verified Diesel at 5 centres (Westfield
    // London/Stratford, Bluewater, Meadowhall, Bullring) before the rebuild
    // session began, so detection-fail-to-drop here is a false negative; the
    // brand passes the rule on the pre-verified seed.
    id: 'B102', name: 'Diesel', cluster: 'Premium Casual',
    womenswear: true, menswear: true, childrenswear: false,
    manualCheck: true, url: 'https://www.diesel.com/en-gb/',
  },
];

// Brands that require manual weekly check (bot-protected)
export const manualCheckBrands = brands.filter(b => b.manualCheck);

// Brands eligible for automated scraping
export const autoBrands = brands.filter(b => !b.manualCheck);
