-- Migration: add Claude-generated narrative to centre_seer_scores
--
-- Stores a 1-2 sentence trend narrative per centre per day, generated by
-- summarise.js after score.js writes the day's row. The front-end reads
-- this column directly and falls back to a template if it's null.
--
-- Idempotent: safe to re-run.

ALTER TABLE centre_seer_scores
  ADD COLUMN IF NOT EXISTS narrative              TEXT,
  ADD COLUMN IF NOT EXISTS narrative_generated_at TIMESTAMPTZ;

-- Anon read on centre_seer_scores is already granted (see
-- 20260503_grant_anon_read.sql) with USING (true), so the new columns are
-- automatically readable via PostgREST. No further policy changes needed.
