-- 20260504_reset_tide_history.sql
--
-- ⚠️ NEUTRALIZED 2026-05-31 — this migration is now an INERT no-op. ⚠️
--
-- It was a ONE-SHOT data reset that ran once on 2026-05-04 to drop noisy
-- pre-detector-fix history. Its destructive statements have been commented out
-- so it can NEVER wipe score history again on a `supabase db reset`, a fresh
-- environment provision, or any other replay of the migrations directory.
-- Score history (centre_seer_scores + centres.tide_history) must never be
-- destroyed by a migration replay. See TECH-DEBT-AUDIT-2026-05-31.md (D2).
--
-- The original (now disabled) operation, for the historical record:
--   1. Snapshotted current state into archive tables (reversible)
--   2. Deleted centre_seer_scores rows from before today
--   3. Truncated each centres.tide_history to just today's verified entry
--
-- DO NOT re-enable these statements. If a one-off reset is ever genuinely
-- needed again, do it from a deliberately-run script in scripts/ — never from
-- the auto-applied migrations directory.

-- ── DISABLED 2026-05-31 — original destructive body kept commented for the record ──
--
-- -- 1. Snapshot — full audit copy of pre-reset state
-- CREATE TABLE IF NOT EXISTS centre_seer_scores_archive_20260504 AS
--   SELECT * FROM centre_seer_scores;
--
-- CREATE TABLE IF NOT EXISTS centres_tide_history_archive_20260504 AS
--   SELECT id, name, tide_history FROM centres;
--
-- -- 2. Drop pre-today scores
-- DELETE FROM centre_seer_scores WHERE score_date < CURRENT_DATE;
--
-- -- 3. Truncate each centre's tide_history to today's seed (or empty)
-- UPDATE centres c
-- SET tide_history = COALESCE(
--   (
--     SELECT jsonb_build_array(
--       jsonb_build_object(
--         'date', s.score_date::text,
--         'score', s.tide_score
--       )
--     )
--     FROM centre_seer_scores s
--     WHERE s.centre_id = c.id
--       AND s.score_date = CURRENT_DATE
--   ),
--   '[]'::jsonb
-- );

-- Intentionally does nothing now.
SELECT 1;
